FROM datawookie/ib-gateway:1026.1h

# ── OPTIONAL: add a system JRE ────────────────────────────────
USER root
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive \
    apt-get install -y --no-install-recommends openjdk-8-jre-headless \
 && rm -rf /var/lib/apt/lists/*